[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = [
    "mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views bootstrap/cache",
    "chmod -R 777 storage bootstrap/cache",
    "composer install --no-dev --optimize-autoloader",
    "chmod +x start.sh"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache"
]

[start]
cmd = "./start.sh"
