[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = [
    "mkdir -p bootstrap/cache storage/logs storage/framework/cache storage/framework/sessions storage/framework/views",
    "chmod -R 777 storage bootstrap/cache",
    "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache"
]

[start]
cmd = "php artisan config:clear && php artisan cache:clear && sleep 10 && php artisan migrate:fresh --force && php artisan db:seed --force && php export_railway_data.php && php artisan serve --host=0.0.0.0 --port=$PORT"
