[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[build]
buildHash = "force-php81-v5"

[phases.install]
cmds = [
    "mkdir -p bootstrap/cache storage/logs storage/framework/cache storage/framework/sessions storage/framework/views",
    "chmod -R 777 storage bootstrap/cache",
    "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
    "echo '=== BUILD STARTED ===' && date",
    "echo 'PHP Version:' && php --version",
    "php artisan config:cache",
    "php artisan route:cache",
    "echo '=== BUILD COMPLETED ===' && date"
]

[start]
cmd = "php artisan config:clear && php artisan cache:clear && sleep 10 && php artisan migrate:fresh --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
