[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-scripts']

[phases.build]
cmds = [
  'php artisan key:generate --force || true',
  'php artisan config:cache || echo "Config cache skipped"',
  'php artisan route:cache || echo "Route cache skipped"',
  'php artisan view:cache || echo "View cache skipped"'
]

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
